SERVER_PORT: 8082

server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework:
      web: INFO
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
  # static-path-pattern: /static/**


webmvc:
  config:
    file:
      maxSize: 20848820

tpcms:
  credentials:
    appUserName: TPCMS_2020@LibYa
    appPassword: a0f983787949b1089c85d013ad5d051b745ff15d
    appSmartSecurityKey: 6a720256-552f-4dd8-a5ca-d6304374ab1c
