SERVER_PORT: 8080

server:
  port: ${SERVER_PORT}

logging:
  level:
    org.springframework:
      web: INFO
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
  # static-path-pattern: /static/**


webmvc:
  config:
    file:
      maxSize: 20848820